### ISSUE TITLE
Missing torch.minimum (with an alternative raising exception)

### ISSUE THREAD

**Issue by pkese** [dotnet/TorchSharp#353]
`torch.minimum(a,b)` is missing.
`torch.min(a,b)` is available but causes exception:
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'THSTensor_minimum' in shared library 'LibTorchSharp'.
   at TorchSharp.torch.Tensor.THSTensor_minimum(IntPtr tensor, IntPtr other)
   at TorchSharp.torch.Tensor.min(Tensor other)
   at TorchSharp.torch.min(Tensor input, Tensor other)
```

Luckily `a.min(b)` works.

**Comment by NiklasGustafsson** [comment]
Thanks for reporting. This mixup will be cleared up in PR #352
