### ISSUE TITLE
System.NotSupportedException

### ISSUE THREAD

**Issue by StuvX** [dotnet/TorchSharp#494]
I'm struggling to get scripts to work on macOS. 

I'm on macOS Monterey, version 12.0.1. Following the tutorial I add:
#r "nuget: TorchSharp-cpu"

at the top of my script, but when I try:
let t = torch.ones(3,4)

I get the following error: 
This application uses TorchSharp but doesn't contain reference to either libtorch-cuda-11.3-osx-x64 or libtorch-cpu, 1.10.0.1. 

The native dlls and dylibs are located where the error message says it's is looking for them, but they won't load. I wonder if this is some funny macOS permissions error??? Can you help me understand where I've gone wrong?

I've tried NativeLibraryLoad using my PyTorch instance of libtorch and to point it to the .nuget package libtorch, but to no avail. The full error is as follows (not sure where Step 2 is):

This application uses TorchSharp but doesn't contain reference to either libtorch-cuda-11.3-osx-x64 or libtorch-cpu, 1.10.0.1. Consider either referencing one of these packages or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-libLibTorchSharp.dylib) explicitly for a Python install or a download of libtorch.so/torch.dll. See https://github.com/dotnet/TorchSharp/issues/169.". Trace from LoadNativeBackend:

TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = False

Step 1 - First try regular load of native libtorch binaries.

    Trying to load native component torch_cpu relative to /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/TorchSharp.dll
    Trying to load native component LibTorchSharp relative to /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/TorchSharp.dll
    Failed to load native component LibTorchSharp relative to /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/TorchSharp.dll
    Result from regular native load of LibTorchSharp is False

Step 3 - Alternative load from consolidated directory of native binaries from nuget packages

    torchsharpLoc = /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1
    packagesDir = /Users/axolotl/.nuget/packages
    torchsharpHome = /Users/axolotl/.nuget/packages/torchsharp/0.95.4
    Trying dynamic load for .NET/F# Interactive by consolidating native libtorch-cpu-* binaries to /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/cpu...
    Consolidating native binaries, packagesDir=/Users/axolotl/.nuget/packages, packagePattern=libtorch-cpu, packageVersion=1.10.0.1 to target=/Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/Users/axolotl/.nuget/packages/libtorch-cpu/1.10.0.1/runtimes/osx-x64/native
    Consolidating native binaries, packagesDir=/Users/axolotl/.nuget/packages, packagePattern=torchsharp, packageVersion=0.95.4 to target=/Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/Users/axolotl/.nuget/packages/torchsharp/0.95.4/runtimes/osx-x64/native
    Trying to load native component /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/cpu/libLibTorchSharp.dylib
    Failed to load native component /Users/axolotl/.nuget/packages/torchsharp/0.95.4/lib/netcoreapp3.1/cpu/libLibTorchSharp.dylib

   at TorchSharp.torch.LoadNativeBackend(Boolean useCudaBackend, StringBuilder& trace)
   at TorchSharp.torch.InitializeDeviceType(DeviceType deviceType)
   at TorchSharp.torch.InitializeDevice(Device device)
   at TorchSharp.torch.ones(Int64[] size, Nullable`1 dtype, Device device, Boolean requiresGrad)
   at TorchSharp.torch.ones(Int32 rows, Int32 columns, Nullable`1 dtype, Device device, Boolean requiresGrad)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error

**Comment by StuvX** [comment]
now setting the following at the top of the script it fails silently
System.Runtime.InteropServices.NativeLibrary.Load("/Users/axolotl/miniconda3/envs/pt/lib/python3.8/site-packages/torch/lib/libtorch.dylib")

**Comment by StuvX** [comment]
OK - I managed to get a workaround by updating [libtorch to 1.10.1 via homebrew](https://formulae.brew.sh/formula/libtorch#default) ... so there is some issue with the nuget package for TorchSharp-cpu on osx that isn't loading the torch libraries properly, I'll close this for anybody else that might come up against the same issue.
