### ISSUE TITLE
Upgrade binaries to LibTorch 1.12.0

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#664]

**Comment by NiklasGustafsson** [comment]
I'm having a little bit of trouble with this binaries upgrade. 

If anyone is interested in helping me figure out why certain tests just crash the process, I have a branch over in my private fork:

https://github.com/NiklasGustafsson/TorchSharp/tree/1.12

You need to start with a clean folder; downloading 1.12 dependencies will take some time.

**Comment by dayo05** [comment]
I've tried to test the code and I found that it's trying to download 1.11 binary on MacOS. Maybe this is one of the reason? or MacOS support is not in progress?

**Comment by NiklasGustafsson** [comment]
It keeps trying do use 1.11 binaries unless you clear anything that git doesn't manage with:

```
git -xfv .
```

**Comment by kaiidams** [comment]
I see unit tests of TorchSharp with LibTorch 1.11 randomly crashes on my GitHub codespaces.

```sh
$ dotnet test /p:SkipCuda=true --filter "TorchSharp.TestTorchVision"
...
A total of 1 test files matched the specified pattern.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed
Results File: /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/_codespaces-0011ad_2022-09-06_10_30_13.trx

Passed!  - Failed:     0, Passed:     3, Skipped:     0, Total:     3, Duration: 7 s - /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/TorchSharpTest.dll (net5.0)
Test Run Aborted.
```

**Comment by kaiidams** [comment]
Seems to always crash with LibTorch 1.12.0.

```sh
$ dotnet test /p:SkipCuda=true --filter TorchSharp.TestTorchAudioLoadSave.LoadSaveNoBackend 
...
[xUnit.net 00:00:00.91]     TorchSharp.TestTorchAudioLoadSave.LoadSaveNoBackend [FAIL]
  Failed TorchSharp.TestTorchAudioLoadSave.LoadSaveNoBackend [278 ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.Runtime.InteropServices.ExternalException): Tensors of type TensorImpl do not have strides
          Exception raised from strides_custom at ../c10/core/TensorImpl.cpp:383 (most recent call first):
          frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7efd9c182bbe in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
          frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7efd9c15de38 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
          frame #2: c10::TensorImpl::strides_custom() const + 0x75 (0x7efd9c16bc25 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
          frame #3: at::TensorIteratorBase::compute_strides(at::TensorIteratorConfig const&) + 0x1d7 (0x7efd4c3d6897 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #4: at::TensorIteratorBase::build(at::TensorIteratorConfig&) + 0x203 (0x7efd4c3dbcb3 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #5: at::TensorIteratorBase::build_borrowing_binary_op(at::TensorBase const&, at::TensorBase const&, at::TensorBase const&) + 0xb2 (0x7efd4c3dcfe2 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #6: <unknown function> + 0x24e5c55 (0x7efd4d146c55 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #7: <unknown function> + 0x24e5cc0 (0x7efd4d146cc0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #8: at::_ops::mul_Tensor::call(at::Tensor const&, at::Tensor const&) + 0xc4 (0x7efd4cc2d004 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #9: at::native::mul(at::Tensor const&, c10::Scalar const&) + 0x32 (0x7efd4c58e582 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #10: <unknown function> + 0x26078e0 (0x7efd4d2688e0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #11: at::_ops::mul_Scalar::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::Scalar const&) + 0x6c (0x7efd4cbfe91c in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #12: <unknown function> + 0x35346b0 (0x7efd4e1956b0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #13: <unknown function> + 0x3534a83 (0x7efd4e195a83 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #14: at::_ops::mul_Scalar::call(at::Tensor const&, c10::Scalar const&) + 0x149 (0x7efd4cc3e4b9 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
          frame #15: at::Tensor::mul(c10::Scalar const&) const + 0x2b (0x7efd7d6414cb in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libLibTorchSharp.so)
          frame #16: THSTensor_mul_scalar + 0x4e (0x7efd7d638e2e in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libLibTorchSharp.so)
          frame #17: [0x7efdd2e234a0]
          
---- System.Runtime.InteropServices.ExternalException : Tensors of type TensorImpl do not have strides
Exception raised from strides_custom at ../c10/core/TensorImpl.cpp:383 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7efd9c182bbe in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7efd9c15de38 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
frame #2: c10::TensorImpl::strides_custom() const + 0x75 (0x7efd9c16bc25 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libc10.so)
frame #3: at::TensorIteratorBase::compute_strides(at::TensorIteratorConfig const&) + 0x1d7 (0x7efd4c3d6897 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #4: at::TensorIteratorBase::build(at::TensorIteratorConfig&) + 0x203 (0x7efd4c3dbcb3 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #5: at::TensorIteratorBase::build_borrowing_binary_op(at::TensorBase const&, at::TensorBase const&, at::TensorBase const&) + 0xb2 (0x7efd4c3dcfe2 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #6: <unknown function> + 0x24e5c55 (0x7efd4d146c55 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #7: <unknown function> + 0x24e5cc0 (0x7efd4d146cc0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #8: at::_ops::mul_Tensor::call(at::Tensor const&, at::Tensor const&) + 0xc4 (0x7efd4cc2d004 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #9: at::native::mul(at::Tensor const&, c10::Scalar const&) + 0x32 (0x7efd4c58e582 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #10: <unknown function> + 0x26078e0 (0x7efd4d2688e0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #11: at::_ops::mul_Scalar::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::Scalar const&) + 0x6c (0x7efd4cbfe91c in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #12: <unknown function> + 0x35346b0 (0x7efd4e1956b0 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #13: <unknown function> + 0x3534a83 (0x7efd4e195a83 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #14: at::_ops::mul_Scalar::call(at::Tensor const&, c10::Scalar const&) + 0x149 (0x7efd4cc3e4b9 in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libtorch_cpu.so)
frame #15: at::Tensor::mul(c10::Scalar const&) const + 0x2b (0x7efd7d6414cb in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libLibTorchSharp.so)
frame #16: THSTensor_mul_scalar + 0x4e (0x7efd7d638e2e in /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/libLibTorchSharp.so)
frame #17: [0x7efdd2e234a0]

  Stack Trace:
     at TorchSharp.torch.CheckForErrors() in /workspaces/TorchSharp/src/TorchSharp/Torch.cs:line 487
   at TorchSharp.torch.Tensor.mul(Scalar target) in /workspaces/TorchSharp/src/TorchSharp/Tensor/Tensor.Math.cs:line 1513
   at TorchSharp.torch.Tensor.op_Multiply(Scalar left, Tensor right) in /workspaces/TorchSharp/src/TorchSharp/Tensor/Tensor.Math.cs:line 2146
   at TorchSharp.TestTorchAudioLoadSave.make_waveform() in /workspaces/TorchSharp/test/TorchSharpTest/TestTorchAudioLoadSave.cs:line 18
   at TorchSharp.TestTorchAudioLoadSave.<>c.<LoadSaveNoBackend>b__3_1() in /workspaces/TorchSharp/test/TorchSharpTest/TestTorchAudioLoadSave.cs:line 50
----- Inner Stack Trace -----
   at TorchSharp.torch.CheckForErrors() in /workspaces/TorchSharp/src/TorchSharp/Torch.cs:line 487
   at TorchSharp.torch.Tensor.mul(Scalar target) in /workspaces/TorchSharp/src/TorchSharp/Tensor/Tensor.Math.cs:line 1513
   at TorchSharp.torch.Tensor.op_Multiply(Scalar left, Tensor right) in /workspaces/TorchSharp/src/TorchSharp/Tensor/Tensor.Math.cs:line 2146
   at TorchSharp.TestTorchAudioLoadSave.make_waveform() in /workspaces/TorchSharp/test/TorchSharpTest/TestTorchAudioLoadSave.cs:line 18
   at TorchSharp.TestTorchAudioLoadSave.<>c.<LoadSaveNoBackend>b__3_1() in /workspaces/TorchSharp/test/TorchSharpTest/TestTorchAudioLoadSave.cs:line 50
Results File: /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/_codespaces-0011ad_2022-09-06_11_25_04.trx

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - /workspaces/TorchSharp/bin/AnyCPU.Debug/TorchSharpTest/net5.0/TorchSharpTest.dll (net5.0)
```

**Comment by NiklasGustafsson** [comment]
> I see unit tests of TorchSharp with LibTorch 1.11 randomly crashes on my GitHub codespaces.

The intermittent test failures with 1.11 are, we believe, related to concurrency issues caused by the xUnit framework running things in parallel. The 1.12 issues are unrelated and not intermittent.

**Comment by dayo05** [comment]
I want to test for arm binary of libtorch but the script is trying to download only amd64 based runtime. Is there any way to force-set the binary to use on build / test with script?

**Comment by dayo05** [comment]
@NiklasGustafsson bump
